.libPaths("/home/jpyanez/mader/mb_lightweight/rpackages")
install.packages("MBHdesign", repos='http://cran.us.r-project.org')
install.packages("spsurvey", repos='http://cran.us.r-project.org')
install.packages("maptools", repos='http://cran.us.r-project.org')
install.packages("rgeos", repos='http://cran.us.r-project.org')
install.packages("raster", repos='http://cran.us.r-project.org')
install.packages("car", repos='http://cran.us.r-project.org')
install.packages("sf", repos='http://cran.us.r-project.org')
install.packages("tidyverse", repos='http://cran.us.r-project.org')
install.packages("sp", repos='http://cran.us.r-project.org')
install.packages("rgdal", repos='http://cran.us.r-project.org')
install.packages("lakemorpho", repos='http://cran.us.r-project.org')
install.packages("dplyr", repos='http://cran.us.r-project.org')
install.packages("car", repos='http://cran.us.r-project.org')
install.packages("doBy", repos='http://cran.us.r-project.org')
install.packages("gdata", repos='http://cran.us.r-project.org')
install.packages("ggplot2", repos='http://cran.us.r-project.org')
install.packages("nngeo", repos='http://cran.us.r-project.org')
install.packages("reshape2", repos='http://cran.us.r-project.org')
install.packages("viridis", repos='http://cran.us.r-project.org')
install.packages("scales", repos='http://cran.us.r-project.org')
install.packages("parallel", repos='http://cran.us.r-project.org')
install.packages("doSNOW", repos='http://cran.us.r-project.org')
install.packages("foreach", repos='http://cran.us.r-project.org')
install.packages("vegan", repos='http://cran.us.r-project.org')

